/**
 * Data-access for persisted AI-agent runs (`admin_agent_reports`).
 *
 * Every agent run in AgentsView is saved here so the team can revisit the
 * history and filter by agent, date, and status — the "Access historical
 * reports generated by each agent" item from the feedback.
 */

import { supabase } from './supabase';
import type { AgentReportRecord, AgentReportStatus } from './types';

type ReportRow = {
  id: string;
  agent_id: string;
  agent_label: string;
  status: string;
  report: AgentReportRecord['report'] | null;
  created_by: string | null;
  created_at: string;
  updated_at: string | null;
};

function rowToReport(r: ReportRow): AgentReportRecord {
  return {
    id: r.id,
    agentId: r.agent_id,
    agentLabel: r.agent_label,
    status: (r.status as AgentReportStatus) ?? 'new',
    report: r.report ?? {},
    createdBy: r.created_by,
    createdAt: r.created_at,
    updatedAt: r.updated_at ?? undefined,
  };
}

export async function fetchReports(): Promise<AgentReportRecord[]> {
  const { data, error } = await supabase
    .from('admin_agent_reports')
    .select('*')
    .order('created_at', { ascending: false });
  if (error) throw error;
  return (data as ReportRow[]).map(rowToReport);
}

export async function saveReport(input: {
  agentId: string;
  agentLabel: string;
  report: AgentReportRecord['report'];
}): Promise<AgentReportRecord> {
  const { data: userData } = await supabase.auth.getUser();
  const { data, error } = await supabase
    .from('admin_agent_reports')
    .insert({
      agent_id: input.agentId,
      agent_label: input.agentLabel,
      report: input.report,
      created_by: userData.user?.id ?? null,
    })
    .select('*')
    .single();
  if (error) throw error;
  return rowToReport(data as ReportRow);
}

export async function setReportStatus(
  id: string,
  status: AgentReportStatus
): Promise<void> {
  const { error } = await supabase
    .from('admin_agent_reports')
    .update({ status })
    .eq('id', id);
  if (error) throw error;
}

export async function deleteReport(id: string): Promise<void> {
  const { error } = await supabase.from('admin_agent_reports').delete().eq('id', id);
  if (error) throw error;
}
