/**
 * Seed corpus — the original ~80 lessons + their tracks, extracted from the
 * legacy Corpus Builder (legacy/index.html). Used by the one-time import on
 * the Export tab to populate the empty Supabase corpus. Content blocks/quizzes
 * are intentionally empty here — they are authored in-app or AI-generated.
 *
 * GENERATED — do not edit by hand. Re-run scripts/gen-seed (see Export view).
 */

import type { Lesson, Track } from './types';

export const SEED_TRACKS: Track[] = [
  {
    "id": "make-your-money-work-or-not",
    "emoji": "💸",
    "nameFr": "Make Your Money Work (or Not)",
    "level": "Débutant",
    "sortOrder": 0
  },
  {
    "id": "psychology-your-worst-enemy",
    "emoji": "🧠",
    "nameFr": "Psychology: Your Worst Enemy",
    "level": "Débutant",
    "sortOrder": 1
  },
  {
    "id": "basic-vocabulary",
    "emoji": "📖",
    "nameFr": "Basic Vocabulary",
    "level": "Débutant",
    "sortOrder": 2
  },
  {
    "id": "etf-the-game-changer",
    "emoji": "🌊",
    "nameFr": "ETF: The Game Changer",
    "level": "Débutant",
    "sortOrder": 3
  },
  {
    "id": "real-estate-myth-or-reality",
    "emoji": "🏠",
    "nameFr": "Real Estate: Myth or Reality?",
    "level": "Intermédiaire",
    "sortOrder": 4
  },
  {
    "id": "crypto",
    "emoji": "₿",
    "nameFr": "Crypto",
    "level": "Intermédiaire",
    "sortOrder": 5
  },
  {
    "id": "taxation-keep-your-money",
    "emoji": "🏛️",
    "nameFr": "Taxation: Keep Your Money",
    "level": "Intermédiaire",
    "sortOrder": 6
  },
  {
    "id": "analysing-a-stock",
    "emoji": "🔬",
    "nameFr": "Analysing a Stock",
    "level": "Intermédiaire",
    "sortOrder": 7
  },
  {
    "id": "macro-markets",
    "emoji": "🌍",
    "nameFr": "Macro & Markets",
    "level": "Intermédiaire",
    "sortOrder": 8
  },
  {
    "id": "retirement-long-term",
    "emoji": "🏖️",
    "nameFr": "Retirement & Long Term",
    "level": "Intermédiaire",
    "sortOrder": 9
  },
  {
    "id": "advanced-strategies",
    "emoji": "🎯",
    "nameFr": "Advanced Strategies",
    "level": "Intermédiaire",
    "sortOrder": 10
  },
  {
    "id": "expert-level",
    "emoji": "🎓",
    "nameFr": "Expert Level",
    "level": "Intermédiaire",
    "sortOrder": 11
  },
  {
    "id": "managing-your-money",
    "emoji": "💰",
    "nameFr": "Managing Your Money",
    "level": "Débutant",
    "sortOrder": 12
  },
  {
    "id": "going-further",
    "emoji": "🚀",
    "nameFr": "Going Further",
    "level": "Intermédiaire",
    "sortOrder": 13
  }
];

export const SEED_LESSONS: Lesson[] = [
  {
    "id": "d1",
    "trackId": "make-your-money-work-or-not",
    "emoji": "🧱",
    "name": "Asset vs Liability: The Rule That Changes Everything",
    "duration": "1 min",
    "coins": 80,
    "xp": 60,
    "tag": "Base",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "d2",
    "trackId": "make-your-money-work-or-not",
    "emoji": "🔇",
    "name": "Inflation: The Silent Thief",
    "duration": "1 min",
    "coins": 80,
    "xp": 60,
    "tag": "Base",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "d3",
    "trackId": "make-your-money-work-or-not",
    "emoji": "⏰",
    "name": "Compound Interest: The Wealth Machine",
    "duration": "1 min",
    "coins": 80,
    "xp": 60,
    "tag": "Base",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "d4",
    "trackId": "make-your-money-work-or-not",
    "emoji": "📅",
    "name": "DCA: Invest Without Overthinking",
    "duration": "1 min",
    "coins": 80,
    "xp": 60,
    "tag": "Stratégie",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "d5",
    "trackId": "make-your-money-work-or-not",
    "emoji": "🥚",
    "name": "Don't Put All Your Eggs in One Basket",
    "duration": "1 min",
    "coins": 80,
    "xp": 60,
    "tag": "Stratégie",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "d6",
    "trackId": "make-your-money-work-or-not",
    "emoji": "📊",
    "name": "The Stock Market: Casino or Wealth Machine?",
    "duration": "1 min",
    "coins": 80,
    "xp": 60,
    "tag": "Base",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "d7",
    "trackId": "make-your-money-work-or-not",
    "emoji": "🇫🇷",
    "name": "PEA, Life Insurance, CTO: Choose the Right Wrapper",
    "duration": "2 min",
    "coins": 100,
    "xp": 75,
    "tag": "Fiscalité",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "d8",
    "trackId": "make-your-money-work-or-not",
    "emoji": "🎯",
    "name": "The SMART Goal in Finance",
    "duration": "1 min",
    "coins": 80,
    "xp": 60,
    "tag": "Pratique",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "d9",
    "trackId": "make-your-money-work-or-not",
    "emoji": "💡",
    "name": "The 50/30/20 Rule",
    "duration": "1 min",
    "coins": 80,
    "xp": 60,
    "tag": "Pratique",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "d10",
    "trackId": "make-your-money-work-or-not",
    "emoji": "🗝️",
    "name": "The 4% Rule: Your Freedom Number",
    "duration": "1 min",
    "coins": 80,
    "xp": 60,
    "tag": "Base",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "p1",
    "trackId": "psychology-your-worst-enemy",
    "emoji": "😱",
    "name": "FOMO: The Fear of Missing Out That Ruins You",
    "duration": "1 min",
    "coins": 80,
    "xp": 60,
    "tag": "Psychologie",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "p2",
    "trackId": "psychology-your-worst-enemy",
    "emoji": "🎭",
    "name": "The Disposition Effect: Selling Too Early, Holding Too Long",
    "duration": "1 min",
    "coins": 80,
    "xp": 60,
    "tag": "Psychologie",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "p3",
    "trackId": "psychology-your-worst-enemy",
    "emoji": "😤",
    "name": "Loss Aversion: Holding onto a Losing Position",
    "duration": "1 min",
    "coins": 80,
    "xp": 60,
    "tag": "Psychologie",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "p4",
    "trackId": "psychology-your-worst-enemy",
    "emoji": "🕶️",
    "name": "Confirmation Bias: You Read What Confirms You",
    "duration": "1 min",
    "coins": 80,
    "xp": 60,
    "tag": "Psychologie",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "p5",
    "trackId": "psychology-your-worst-enemy",
    "emoji": "🎰",
    "name": "Overconfidence: The Lucky Beginner's Trap",
    "duration": "1 min",
    "coins": 80,
    "xp": 60,
    "tag": "Psychologie",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "p6",
    "trackId": "psychology-your-worst-enemy",
    "emoji": "🌊",
    "name": "Herd Behaviour: Don't Follow the Lemmings",
    "duration": "1 min",
    "coins": 80,
    "xp": 60,
    "tag": "Psychologie",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "p7",
    "trackId": "psychology-your-worst-enemy",
    "emoji": "⏳",
    "name": "Delayed Gratification: The Superpower of the Wealthy",
    "duration": "1 min",
    "coins": 80,
    "xp": 60,
    "tag": "Psychologie",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "v1",
    "trackId": "basic-vocabulary",
    "emoji": "💧",
    "name": "Liquidity & Volatility: Two Things Not to Confuse",
    "duration": "1 min",
    "coins": 80,
    "xp": 60,
    "tag": "Vocab",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "v2",
    "trackId": "basic-vocabulary",
    "emoji": "🐂",
    "name": "Bull & Bear: The Two Market Moods",
    "duration": "1 min",
    "coins": 80,
    "xp": 60,
    "tag": "Vocab",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "v3",
    "trackId": "basic-vocabulary",
    "emoji": "💰",
    "name": "Dividends: Getting Paid for Sitting Still",
    "duration": "1 min",
    "coins": 80,
    "xp": 60,
    "tag": "Vocab",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "v4",
    "trackId": "basic-vocabulary",
    "emoji": "📜",
    "name": "Stocks, ETFs, Bonds: The 3 Asset Families",
    "duration": "2 min",
    "coins": 80,
    "xp": 60,
    "tag": "Vocab",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "v5",
    "trackId": "basic-vocabulary",
    "emoji": "🏦",
    "name": "The P/E Ratio: Price-to-Earnings for Beginners",
    "duration": "1 min",
    "coins": 80,
    "xp": 60,
    "tag": "Vocab",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "v6",
    "trackId": "basic-vocabulary",
    "emoji": "📈",
    "name": "Capital Gain, Loss, PnL: Speaking the Right Language",
    "duration": "1 min",
    "coins": 80,
    "xp": 60,
    "tag": "Vocab",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "v7",
    "trackId": "basic-vocabulary",
    "emoji": "⚖️",
    "name": "Risk vs Return: The Basic Trade-off",
    "duration": "1 min",
    "coins": 80,
    "xp": 60,
    "tag": "Vocab",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "a1",
    "trackId": "make-your-money-work-or-not",
    "emoji": "🚀",
    "name": "Your First Investment in 4 Steps",
    "duration": "2 min",
    "coins": 100,
    "xp": 75,
    "tag": "Pratique",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "a2",
    "trackId": "make-your-money-work-or-not",
    "emoji": "🔄",
    "name": "Rebalancing: Sell High, Buy Low Automatically",
    "duration": "1 min",
    "coins": 100,
    "xp": 75,
    "tag": "Pratique",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "a3",
    "trackId": "etf-the-game-changer",
    "emoji": "📊",
    "name": "Reading an ETF Factsheet in 2 Minutes",
    "duration": "2 min",
    "coins": 100,
    "xp": 75,
    "tag": "ETF",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "im1",
    "trackId": "real-estate-myth-or-reality",
    "emoji": "🏠",
    "name": "Rental Property: Myth vs Reality",
    "duration": "2 min",
    "coins": 120,
    "xp": 90,
    "tag": "Immo",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "im2",
    "trackId": "real-estate-myth-or-reality",
    "emoji": "🔑",
    "name": "Real Estate Cash Flow: The Real Calculation",
    "duration": "2 min",
    "coins": 120,
    "xp": 90,
    "tag": "Immo",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "e1",
    "trackId": "etf-the-game-changer",
    "emoji": "🌊",
    "name": "What Exactly Is an ETF?",
    "duration": "1 min",
    "coins": 100,
    "xp": 75,
    "tag": "ETF",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "e2",
    "trackId": "etf-the-game-changer",
    "emoji": "🎯",
    "name": "ETF World vs S&P 500: Which to Choose?",
    "duration": "2 min",
    "coins": 100,
    "xp": 75,
    "tag": "ETF",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "e3",
    "trackId": "etf-the-game-changer",
    "emoji": "💲",
    "name": "TER & Hidden Fees: The Invisible Enemy",
    "duration": "1 min",
    "coins": 100,
    "xp": 75,
    "tag": "ETF",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "e4",
    "trackId": "etf-the-game-changer",
    "emoji": "🏗️",
    "name": "Physical vs Synthetic ETF",
    "duration": "2 min",
    "coins": 100,
    "xp": 75,
    "tag": "ETF",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "e5",
    "trackId": "etf-the-game-changer",
    "emoji": "🔄",
    "name": "Accumulating vs Distributing: Which to Choose?",
    "duration": "1 min",
    "coins": 100,
    "xp": 75,
    "tag": "ETF",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "c1",
    "trackId": "crypto",
    "emoji": "₿",
    "name": "Bitcoin: Store of Value or Speculation?",
    "duration": "2 min",
    "coins": 120,
    "xp": 90,
    "tag": "Crypto",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "c2",
    "trackId": "crypto",
    "emoji": "🔐",
    "name": "Crypto Wallet: Keep Your Keys",
    "duration": "1 min",
    "coins": 120,
    "xp": 90,
    "tag": "Crypto",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "f1",
    "trackId": "taxation-keep-your-money",
    "emoji": "🏛️",
    "name": "The 30% Flat Tax: How It Works",
    "duration": "1 min",
    "coins": 100,
    "xp": 75,
    "tag": "Fiscalité",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "f2",
    "trackId": "taxation-keep-your-money",
    "emoji": "🧾",
    "name": "PEA: The Rules to Know",
    "duration": "2 min",
    "coins": 100,
    "xp": 75,
    "tag": "Fiscalité",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "f3",
    "trackId": "taxation-keep-your-money",
    "emoji": "🛡️",
    "name": "Life Insurance: 8 Years for What Exactly?",
    "duration": "2 min",
    "coins": 100,
    "xp": 75,
    "tag": "Fiscalité",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "f4",
    "trackId": "taxation-keep-your-money",
    "emoji": "🎭",
    "name": "Unrealised vs Realised Gains: The Key Difference",
    "duration": "1 min",
    "coins": 100,
    "xp": 75,
    "tag": "Fiscalité",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "f5",
    "trackId": "taxation-keep-your-money",
    "emoji": "🇫🇷",
    "name": "PER: Tax Relief for Retirement",
    "duration": "2 min",
    "coins": 100,
    "xp": 75,
    "tag": "Fiscalité",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "ana1",
    "trackId": "analysing-a-stock",
    "emoji": "🔬",
    "name": "The P/E Ratio: Valuing a Stock",
    "duration": "2 min",
    "coins": 120,
    "xp": 90,
    "tag": "Analyse",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "ana2",
    "trackId": "analysing-a-stock",
    "emoji": "📊",
    "name": "ROE, ROA, ROCE: Measuring Profitability",
    "duration": "2 min",
    "coins": 120,
    "xp": 90,
    "tag": "Analyse",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "ana3",
    "trackId": "analysing-a-stock",
    "emoji": "💸",
    "name": "Free Cash Flow: The True Health Indicator",
    "duration": "2 min",
    "coins": 120,
    "xp": 90,
    "tag": "Analyse",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "ana4",
    "trackId": "analysing-a-stock",
    "emoji": "📉",
    "name": "Net Debt / EBITDA: Reading Leverage",
    "duration": "2 min",
    "coins": 120,
    "xp": 90,
    "tag": "Analyse",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "ana5",
    "trackId": "analysing-a-stock",
    "emoji": "🎯",
    "name": "Intrinsic Value vs Market Price",
    "duration": "2 min",
    "coins": 120,
    "xp": 90,
    "tag": "Analyse",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "ana6",
    "trackId": "analysing-a-stock",
    "emoji": "🏆",
    "name": "Identifying a Competitive Moat",
    "duration": "2 min",
    "coins": 120,
    "xp": 90,
    "tag": "Analyse",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "ana7",
    "trackId": "analysing-a-stock",
    "emoji": "🌐",
    "name": "Sector Analysis: Understanding the Context",
    "duration": "2 min",
    "coins": 120,
    "xp": 90,
    "tag": "Analyse",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "m1",
    "trackId": "macro-markets",
    "emoji": "🌍",
    "name": "ECB Key Rates: Impact on Your Investments",
    "duration": "2 min",
    "coins": 120,
    "xp": 90,
    "tag": "Macro",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "m2",
    "trackId": "macro-markets",
    "emoji": "📊",
    "name": "Inflation and the Investor: Who Wins, Who Loses",
    "duration": "2 min",
    "coins": 120,
    "xp": 90,
    "tag": "Macro",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "m3",
    "trackId": "macro-markets",
    "emoji": "📉",
    "name": "Economic Cycles: Knowing Where We Are",
    "duration": "2 min",
    "coins": 120,
    "xp": 90,
    "tag": "Macro",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "m4",
    "trackId": "macro-markets",
    "emoji": "🛢️",
    "name": "Commodities: Role in a Portfolio",
    "duration": "2 min",
    "coins": 120,
    "xp": 90,
    "tag": "Macro",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "r1",
    "trackId": "retirement-long-term",
    "emoji": "🏖️",
    "name": "Planning Your Retirement: The Real Numbers",
    "duration": "2 min",
    "coins": 120,
    "xp": 90,
    "tag": "Retraite",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "r2",
    "trackId": "retirement-long-term",
    "emoji": "⏰",
    "name": "Retire at 45: A Realistic FIRE Calculation",
    "duration": "2 min",
    "coins": 120,
    "xp": 90,
    "tag": "Retraite",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "r3",
    "trackId": "retirement-long-term",
    "emoji": "📈",
    "name": "The Time Effect: Why Start Now",
    "duration": "1 min",
    "coins": 120,
    "xp": 90,
    "tag": "Retraite",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "r4",
    "trackId": "retirement-long-term",
    "emoji": "🔒",
    "name": "Retirement Sequencing: Avoiding the Crash at the Wrong Time",
    "duration": "2 min",
    "coins": 120,
    "xp": 90,
    "tag": "Retraite",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "r5",
    "trackId": "retirement-long-term",
    "emoji": "💼",
    "name": "PER vs Life Insurance: Which Retirement Tool?",
    "duration": "2 min",
    "coins": 120,
    "xp": 90,
    "tag": "Retraite",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "r6",
    "trackId": "retirement-long-term",
    "emoji": "🌐",
    "name": "Annuities vs Capital: How to Finance Your Freedom",
    "duration": "2 min",
    "coins": 120,
    "xp": 90,
    "tag": "Retraite",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "s1",
    "trackId": "advanced-strategies",
    "emoji": "🎯",
    "name": "Core / Satellite: The Winning Portfolio Structure",
    "duration": "2 min",
    "coins": 150,
    "xp": 113,
    "tag": "Stratégie",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "s2",
    "trackId": "advanced-strategies",
    "emoji": "📐",
    "name": "Asset Allocation: The Decision That Matters Most",
    "duration": "2 min",
    "coins": 150,
    "xp": 113,
    "tag": "Stratégie",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "s3",
    "trackId": "advanced-strategies",
    "emoji": "🔄",
    "name": "Momentum vs Value: Two Opposing Philosophies",
    "duration": "2 min",
    "coins": 150,
    "xp": 113,
    "tag": "Stratégie",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "s4",
    "trackId": "advanced-strategies",
    "emoji": "🛡️",
    "name": "Hedging: Protecting Yourself Without Going Broke",
    "duration": "2 min",
    "coins": 150,
    "xp": 113,
    "tag": "Stratégie",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "s5",
    "trackId": "advanced-strategies",
    "emoji": "📊",
    "name": "Backtesting: Testing a Strategy on Past Data",
    "duration": "2 min",
    "coins": 150,
    "xp": 113,
    "tag": "Stratégie",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "s6",
    "trackId": "advanced-strategies",
    "emoji": "🎲",
    "name": "Position Sizing: Never Go All-In",
    "duration": "1 min",
    "coins": 150,
    "xp": 113,
    "tag": "Stratégie",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "ex1",
    "trackId": "expert-level",
    "emoji": "🎓",
    "name": "Options: Calls and Puts Simply Explained",
    "duration": "3 min",
    "coins": 200,
    "xp": 150,
    "tag": "Expert",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "ex2",
    "trackId": "expert-level",
    "emoji": "📊",
    "name": "DCF Model: Valuing a Company",
    "duration": "3 min",
    "coins": 200,
    "xp": 150,
    "tag": "Expert",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "ex3",
    "trackId": "expert-level",
    "emoji": "🌐",
    "name": "Hedge Funds: How They Really Make Money",
    "duration": "3 min",
    "coins": 200,
    "xp": 150,
    "tag": "Expert",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "ex4",
    "trackId": "expert-level",
    "emoji": "⚡",
    "name": "HFT: High-Frequency Trading Demystified",
    "duration": "2 min",
    "coins": 200,
    "xp": 150,
    "tag": "Expert",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "ex5",
    "trackId": "expert-level",
    "emoji": "📐",
    "name": "Modern Portfolio Theory (Markowitz)",
    "duration": "3 min",
    "coins": 200,
    "xp": 150,
    "tag": "Expert",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "ex6",
    "trackId": "expert-level",
    "emoji": "🔮",
    "name": "Technical Analysis: Does It Really Work?",
    "duration": "2 min",
    "coins": 200,
    "xp": 150,
    "tag": "Expert",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "ex7",
    "trackId": "expert-level",
    "emoji": "🏦",
    "name": "How an IPO Works",
    "duration": "2 min",
    "coins": 200,
    "xp": 150,
    "tag": "Expert",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "g1",
    "trackId": "managing-your-money",
    "emoji": "💰",
    "name": "Emergency Fund: How Much Exactly?",
    "duration": "1 min",
    "coins": 80,
    "xp": 60,
    "tag": "Pratique",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "g2",
    "trackId": "managing-your-money",
    "emoji": "🎯",
    "name": "Zero-Based Budget: Taking Back Control",
    "duration": "2 min",
    "coins": 80,
    "xp": 60,
    "tag": "Pratique",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "g3",
    "trackId": "managing-your-money",
    "emoji": "💳",
    "name": "High-Interest Debt: The Absolute Priority",
    "duration": "1 min",
    "coins": 80,
    "xp": 60,
    "tag": "Pratique",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "g4",
    "trackId": "managing-your-money",
    "emoji": "🏦",
    "name": "Bank Interest: How Banks Profit from You",
    "duration": "1 min",
    "coins": 80,
    "xp": 60,
    "tag": "Pratique",
    "level": "Débutant",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "ad1",
    "trackId": "going-further",
    "emoji": "🚀",
    "name": "Investing in Startups: The Guide",
    "duration": "3 min",
    "coins": 150,
    "xp": 113,
    "tag": "Stratégie",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "ad2",
    "trackId": "going-further",
    "emoji": "🌍",
    "name": "International Investing: Currency Risk",
    "duration": "2 min",
    "coins": 150,
    "xp": 113,
    "tag": "Macro",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  },
  {
    "id": "ad3",
    "trackId": "going-further",
    "emoji": "🏗️",
    "name": "SCPI: Real Estate Without the Management Hassle",
    "duration": "2 min",
    "coins": 150,
    "xp": 113,
    "tag": "Immo",
    "level": "Intermédiaire",
    "blocks": [],
    "quizzes": [],
    "translations": {},
    "status": "published"
  }
];
