/**
 * TACTIC ACADEMY — Complete Syllabus A–H (English).
 *
 * The canonical Domain → Module → Lesson hierarchy from the course syllabus
 * PDF: 8 domains, 43 modules, 516 lesson items. Used by the "Import full
 * syllabus" action to scaffold the corpus. Lessons import as draft metadata
 * (titles only) — content blocks/quizzes are authored or AI-generated after.
 *
 * GENERATED from TACTIC_ACADEMY_SYLLABUS_ENGLISH — keep in sync with the PDF.
 */

export type SyllabusModule = {
  title: string;
  coreQuestion: string;
  lessons: string[];
};

export type SyllabusDomain = {
  code: string; // 'A'..'H'
  name: string;
  emoji: string;
  objective: string;
  modules: SyllabusModule[];
};

export const SYLLABUS: SyllabusDomain[] = [
  {
    code: 'A',
    name: 'Financial Survival',
    emoji: '🛟',
    objective:
      'Transform a person who is controlled by money into a person capable of controlling their financial flows, protecting their capital, understanding inflation and debt, automating savings, and laying the foundations for rational wealth building.',
    modules: [
      {
        title: 'Why Your Money Loses Value',
        coreQuestion: 'Why can someone work their whole life without building wealth?',
        lessons: [
          'The salary trap: high income does not mean wealth',
          'Inflation and purchasing power: why idle money rarely comes without a cost',
          'Money creation: understanding central banks and money without jargon',
          'Assets vs. liabilities: what feeds your wealth and what drains it',
          'Compound interest: why time amplifies small decisions',
          'The real cost of recurring expenses',
          'Lifestyle inflation: why additional income disappears',
          'Personal financial statement: assets, liabilities, income, expenses',
          'The difference between surviving, securing, and building',
          'The three financial mistakes that destroy a trajectory',
          'Identify invisible leaks in your financial flows',
          'First financial reset: complete snapshot of your situation',
        ],
      },
      {
        title: 'Regaining Control of Your Money',
        coreQuestion: 'Why do most people manage their finances randomly?',
        lessons: [
          'Build your first intelligent budget',
          'The 50/30/20 rule: a useful tool, not an absolute truth',
          'Classify expenses: vital, useful, status-driven, destructive',
          'Expenses that build freedom vs. expenses that maintain dependency',
          'Create an automatic savings system',
          'The emergency fund: size, role, vehicle, and limits',
          'Get out of debt intelligently',
          'Understand the true cost of credit',
          'Why banks love poorly organized individuals',
          'Build your financial dashboard',
          'Automate transfers, alerts, and simple decisions',
          'Mission: regain control in 30 days',
        ],
      },
      {
        title: 'Why Your Brain Destroys Your Money',
        coreQuestion: 'Why do intelligent people make catastrophic financial decisions?',
        lessons: [
          'The human brain is not built for investing',
          'FOMO: fear of missing an opportunity',
          'Loss aversion: why losing hurts more than winning feels good',
          'Confirmation bias: seeking what is reassuring rather than what is true',
          'Overconfidence and the illusion of competence',
          'Herd behaviour and financial contagion',
          'Finance influencers and emotional manipulation',
          'The illusion of quick wealth',
          'Why losses destroy rationality',
          'Discipline: the most profitable financial skill',
          'How investors who survive think',
          'Build an antifragile financial brain',
        ],
      },
      {
        title: 'Why Not Investing Is Riskier Than Investing',
        coreQuestion: 'Why can leaving your money idle be a losing strategy?',
        lessons: [
          'Saving vs. investing: two different functions',
          'The hidden cost of inaction',
          'Why wealthy people own assets',
          'The major asset classes',
          'Return vs. risk: the basic language of investing',
          'Compound interest applied to investing',
          'DCA: investing without predicting the market',
          'Why individuals often buy at the wrong time',
          'Classic beginner mistakes',
          'First simple exposure to markets',
          'Build a first simple portfolio',
          'Mission: make your first rational investment',
        ],
      },
      {
        title: 'Why Investing Without a Portfolio Leads to Chaos',
        coreQuestion: 'Why does buying assets without a strategy destroy performance?',
        lessons: [
          'Risk profile: horizon, tolerance, loss capacity',
          'What is a portfolio?',
          'Why putting everything in the same place is dangerous',
          'Diversification: reducing risk without giving up all return',
          'Correlation: the most important hidden concept',
          'ETF: a simple tool for diversification',
          'Build a simple portfolio',
          'Rebalancing: sell a little of what has risen, buy what has fallen',
          'Why fees destroy performance',
          'Basic tax wrappers',
          'Build your wealth-building machine',
          'Mission: formalize your personal investment policy',
        ],
      },
    ],
  },
  {
    code: 'B',
    name: 'Psychology & Behaviour',
    emoji: '🧠',
    objective:
      'Transform an emotionally reactive person into a psychologically stable investor, capable of resisting cognitive biases, crowds, media noise, temporary losses, and promises of quick wealth.',
    modules: [
      {
        title: 'Why People Remain Psychologically Trapped',
        coreQuestion: 'Why do many people remain stuck despite their knowledge?',
        lessons: [
          'The relationship with money inherited from family and social background',
          'Money, status, and social comparison',
          'Why immediate comfort often beats future freedom',
          'Emotional consumption and psychological compensation',
          "The identity trap: 'I am not someone who invests'",
          'Limiting beliefs about the rich, markets, and risk',
          'Financial procrastination',
          'Why complexity often serves as an excuse',
          'Change your informational environment',
          'Define an adult financial identity',
          'Replace guilt with a system',
          'First psychological reset',
        ],
      },
      {
        title: 'The Human Brain Against Financial Markets',
        coreQuestion: 'Why is the human brain poorly adapted to markets?',
        lessons: [
          'Survival instinct vs. rational thought',
          'Dopamine, reward, and impulsive trading',
          'Uncertainty, stress, and the need for certainty',
          'Fast thinking vs. slow thinking',
          'Why markets exploit human emotions',
          'The biology of panic selling',
          'Why humans imitate crowds',
          'The pleasure of winning vs. the pain of losing',
          'Why speculation can become addictive',
          'Decision fatigue and information overload',
          'Build emotional distance',
          'First anti-impulsivity protocol',
        ],
      },
      {
        title: 'Cognitive Biases That Destroy Investors',
        coreQuestion: 'Why does our brain manipulate our perception of risk?',
        lessons: [
          'Confirmation bias',
          'Loss aversion',
          'Overconfidence',
          'Recency bias',
          'Anchoring bias',
          'Availability bias',
          'Survivorship bias',
          'Narrative bias',
          'Familiarity bias',
          'Illusion of control',
          'Herd bias',
          'Anti-bias checklist before any decision',
        ],
      },
      {
        title: 'Why Individuals Panic During Crises',
        coreQuestion: 'Why does a crisis transform a rational strategy into a forced sale?',
        lessons: [
          'The emotional cycle of markets',
          'Euphoria, denial, fear, capitulation',
          'Financial bubbles and collective acceleration',
          'Panic selling: mechanism and prevention',
          'Drawdown: living through a decline without destroying the plan',
          'The role of media in amplifying fear',
          'Why temporary losses become permanent',
          'Pre-written crisis scenarios',
          'Pre-commitment: decide before emotion appears',
          'Psychological liquidity: keep cash in order to sleep',
          'Analyze a crisis after the fact',
          'Personal anti-crisis plan',
        ],
      },
      {
        title: 'Discipline, Systems, and Long-Term Behaviour',
        coreQuestion: 'How can one become predictable in an unpredictable environment?',
        lessons: [
          'Why discipline must be replaced by systems',
          'Monthly financial routines',
          'Investment journal and emotional journal',
          'Checklists before buying, selling, or reallocating',
          'Written portfolio rules',
          'Reduce unnecessary decisions',
          'Automate what should be automated',
          'Know how to do nothing',
          'Measure behaviour rather than only performance',
          'Build a low-noise environment',
          'Remain rational after a major gain',
          'Personal financial behaviour system',
        ],
      },
    ],
  },
  {
    code: 'C',
    name: 'First Investments',
    emoji: '🌱',
    objective:
      'Transform a person who does not understand financial products into an autonomous investor capable of identifying the major asset classes, their risks, their uses, their fees, and their role within a wealth strategy.',
    modules: [
      {
        title: 'Understanding Stocks as an Owner',
        coreQuestion: 'What are you really buying when you buy a stock?',
        lessons: [
          'What is a stock?',
          'Why companies issue shares',
          'How a stock gains value',
          'Dividends and share buybacks',
          'Common shares, preferred shares, and share classes',
          'Stock market indices',
          'Why stocks rise over the long term',
          'The risks of stocks',
          'How to buy a stock',
          'Why most people lose money with individual stocks',
          'When stocks are appropriate',
          'Build your first equity exposure',
        ],
      },
      {
        title: 'Understanding Bonds',
        coreQuestion: 'Why do wealthy people lend while individuals take on debt?',
        lessons: [
          'What is a bond?',
          'Governments vs. companies',
          'Coupon, price, yield, and maturity',
          'The relationship between interest rates and bonds',
          'Duration and sensitivity to rates',
          'Credit rating',
          'Why bonds are useful in a portfolio',
          'Bond risks',
          'Government bonds',
          'Corporate bonds',
          'Inflation-linked bonds',
          'Build your first bond allocation',
        ],
      },
      {
        title: 'ETFs: The Silent Revolution',
        coreQuestion: 'Why have ETFs changed modern investing?',
        lessons: [
          'What is an ETF?',
          'Why ETFs are powerful',
          'Physical ETF vs. synthetic ETF',
          'Accumulating ETF vs. distributing ETF',
          'Major global ETFs',
          'Sector ETFs',
          'Bond ETFs',
          'Smart beta ETFs',
          'The real risks of ETFs',
          'Why ETFs often beat individual investors',
          'How to choose an ETF intelligently',
          'Build a simple ETF portfolio',
        ],
      },
      {
        title: 'Understanding Financial Statements',
        coreQuestion: 'How do you read a company before buying its stock?',
        lessons: [
          'Why financial statements exist',
          'Balance sheet: what the company owns and owes',
          'Income statement: sales, margins, and profits',
          'Cash flow statement',
          'Debt, cash, and solvency',
          'Free cash flow',
          'Capex and investment needs',
          'Quality of revenue',
          'Read an annual report',
          'Accounting red flags',
          'Compare two companies',
          'Synthesis: read a company in 30 minutes',
        ],
      },
      {
        title: 'Essential Financial Ratios',
        coreQuestion: 'Which figures make it possible to assess a company quickly?',
        lessons: [
          'P/E ratio: price paid for earnings',
          'Price-to-book and its limits',
          'EV/EBITDA',
          'Gross margin, operating margin, net margin',
          'ROE',
          'ROIC',
          'Net debt/EBITDA',
          'Current ratio and liquidity',
          'Free cash flow yield',
          'Payout ratio',
          'Compare ratios by sector',
          'Build a simple analysis grid',
        ],
      },
      {
        title: 'Real Estate: Investment or Emotional Trap?',
        coreQuestion: 'Why does real estate fascinate individuals so much?',
        lessons: [
          'Why real estate is psychologically reassuring',
          'Primary residence vs. investment',
          'Buying vs. renting',
          'Rental property',
          'Mortgage credit and leverage',
          'Gross, net, and net-net yield',
          'Real estate risks',
          'What is an SCPI?',
          'SCPI vs. direct real estate',
          'LMNP and taxation',
          'Listed real estate and property companies',
          'Build your first real estate strategy',
        ],
      },
      {
        title: 'Crypto: Financial Revolution or Speculation Machine?',
        coreQuestion: 'Why do cryptocurrencies attract so many investors?',
        lessons: [
          'What is a cryptocurrency?',
          'Why Bitcoin exists',
          'Blockchain and digital scarcity',
          'Ethereum and smart contracts',
          'Stablecoins',
          'Wallets, private keys, and security',
          'Why cryptocurrencies are so volatile',
          'Major crypto mistakes',
          'Staking, yield, and risks',
          'NFTs and digital assets',
          'Frauds, Ponzi schemes, and crypto influencers',
          'Rational crypto exposure',
        ],
      },
      {
        title: 'Building Your First Investment System',
        coreQuestion: 'How do you move from an isolated purchase to a coherent strategy?',
        lessons: [
          'Define your financial objective',
          'Choose your asset classes',
          'Determine your horizon',
          'Build a simple allocation',
          'Choose your investment vehicles',
          'Automate investing',
          'Limit fees',
          'Rebalance without emotion',
          'Monitor your portfolio without obsession',
          'Avoid over-optimization',
          'Document your strategy',
          'Mission: first complete investment system',
        ],
      },
    ],
  },
  {
    code: 'D',
    name: 'Building a Portfolio',
    emoji: '🏗️',
    objective:
      'Transform a product-by-product investor into a portfolio builder capable of combining assets, risks, time horizons, and economic regimes into a robust architecture.',
    modules: [
      {
        title: 'What Is an Intelligent Portfolio?',
        coreQuestion: 'Why is one good isolated asset not enough?',
        lessons: [
          'Portfolio: practical definition',
          'The role of each building block',
          'Expected return',
          'Volatility',
          'Drawdown',
          'Correlation',
          'Naive diversification vs. real diversification',
          'Specific risk vs. systemic risk',
          'Defensive assets and offensive assets',
          'The portfolio as a system',
          'Monitoring indicators',
          'Write a personal investment policy',
        ],
      },
      {
        title: 'Economic Cycles and Markets',
        coreQuestion: 'Why do the same assets not win in all environments?',
        lessons: [
          'Economic cycle: expansion, slowdown, recession, recovery',
          'Inflation',
          'Deflation',
          'Stagflation',
          'Interest rates',
          'Central banks',
          'Bond market',
          'Equity market',
          'Dollar and global liquidity',
          'Financial crises',
          'Geopolitics and energy',
          'Simple macro reading table',
        ],
      },
      {
        title: 'Asset Allocation According to Macro Regimes',
        coreQuestion: 'How can one adapt a portfolio without becoming a macro speculator?',
        lessons: [
          'Strategic vs. tactical allocation',
          'Growth portfolio',
          'Defensive portfolio',
          'All Weather',
          'Risk Parity',
          'Cash as an option',
          'Gold and real assets',
          'Real estate in the allocation',
          'Bonds according to the cycle',
          'Equities according to the cycle',
          'Regime-based rebalancing',
          'Build your target allocation',
        ],
      },
      {
        title: 'Risk Management and Financial Survival',
        coreQuestion: 'Why does survival matter more than outperformance?',
        lessons: [
          'Risk of ruin',
          'Position sizing',
          'Leverage',
          'Maximum acceptable drawdown',
          'VaR: intuition and limits',
          'CVaR',
          'Stress tests',
          'Historical scenarios',
          'Correlations during crises',
          'Liquidity during crises',
          'Antifragility',
          'Portfolio defence plan',
        ],
      },
      {
        title: 'Rebalancing, Fees, and Taxation',
        coreQuestion: 'How can one keep more net performance?',
        lessons: [
          'Why rebalance',
          'Calendar rebalancing',
          'Threshold-based rebalancing',
          'Visible fees and invisible fees',
          'Turnover and taxation',
          'PEA',
          'CTO',
          'Life insurance',
          'PER',
          'Real estate taxation',
          'Order of use of tax wrappers',
          'Annual portfolio checklist',
        ],
      },
    ],
  },
  {
    code: 'E',
    name: 'Understanding Markets',
    emoji: '📊',
    objective:
      'Transform an investor who watches prices into an investor capable of understanding the forces that move markets: rates, liquidity, cycles, flows, expectations, regulation, and market structure.',
    modules: [
      {
        title: 'Why Markets Move',
        coreQuestion: 'Why do prices change even when companies do not change?',
        lessons: [
          'Price, value, and expectations',
          'Supply and demand for capital',
          'Liquidity',
          'Risk-free rate',
          'Risk premium',
          'News vs. surprise',
          'Investor flows',
          'Market narratives',
          'Momentum',
          'Volatility',
          'The role of market makers',
          'Read a market movement without overinterpreting it',
        ],
      },
      {
        title: 'Central Banks, Rates, and Liquidity',
        coreQuestion: 'Why can a few rate decisions move all assets?',
        lessons: [
          'Central bank mandate',
          'Policy rates',
          'Yield curve',
          'Quantitative easing',
          'Quantitative tightening',
          'Monetary transmission',
          'Expected inflation',
          'Real rates',
          'Dollar funding',
          'Financial conditions',
          'Effects on equities and bonds',
          'Rates-liquidity dashboard',
        ],
      },
      {
        title: 'Equity Markets and Microstructure',
        coreQuestion: 'What really happens between an order and a price?',
        lessons: [
          'Primary market and secondary market',
          'Initial public offering',
          'Order book',
          'Bid-ask spread',
          'Market order vs. limit order',
          'Liquidity and depth',
          'Auction fixing and continuous trading',
          'Market makers',
          'Dark pools and internalization',
          'Intraday volatility',
          'Execution cost',
          'Good order practices for individuals',
        ],
      },
      {
        title: 'Bond Markets and Credit',
        coreQuestion: 'Why does the bond market often drive other markets?',
        lessons: [
          'Sovereign debt',
          'Corporate debt',
          'Nominal rate vs. real rate',
          'Credit spread',
          'Investment grade vs. high yield',
          'Default risk',
          'Aggregate market duration',
          'Yield curve and recession',
          'Banks and credit',
          'Bond liquidity crises',
          'Credit indicators to monitor',
          'Read the signal from the bond market',
        ],
      },
      {
        title: 'Financial Crises and Market Regimes',
        coreQuestion: 'Why are crises similar without being identical?',
        lessons: [
          'Speculative bubble',
          'Leverage',
          'Minsky moment',
          'Banking crisis',
          'Sovereign crisis',
          'Currency crisis',
          'Liquidity crisis',
          'Inflationary crisis',
          'Contagion',
          'Response from authorities',
          'Opportunities and traps in crises',
          'Build a historical memory of crises',
        ],
      },
    ],
  },
  {
    code: 'F',
    name: 'Analysing Assets',
    emoji: '🔬',
    objective:
      "Transform a buyer of financial products into an evaluator capable of understanding an asset's quality, price, risk, expected return, and limitations.",
    modules: [
      {
        title: 'Reading a Company Like an Investor',
        coreQuestion: 'Why can a good company be a bad investment?',
        lessons: [
          'Business model',
          'Moat',
          'Growth',
          'Margins',
          'Capital intensity',
          'Quality of management',
          'Capital allocation',
          'Debt and solvency',
          'Free cash flow',
          'Sustainable competitive advantage',
          'Sector risks',
          'Investment thesis',
        ],
      },
      {
        title: 'Valuing a Stock',
        coreQuestion: 'How can one estimate what an asset is worth without believing in a magic formula?',
        lessons: [
          'Price vs. value',
          'Valuation multiples',
          'P/E ratio and limits',
          'EV/EBITDA and limits',
          'DCF: general logic',
          'WACC',
          'Terminal growth rate',
          'Margin of safety',
          'Valuation scenarios',
          'Sensitivity of assumptions',
          'Relative valuation',
          'Decide despite uncertainty',
        ],
      },
      {
        title: 'Analysing Funds and ETFs',
        coreQuestion: 'How can you know whether a collective product deserves a place?',
        lessons: [
          'Tracked index',
          'Replication method',
          'Ongoing charges',
          'Tracking error',
          'Fund liquidity',
          'Assets under management and closure risk',
          'Accumulating vs. distributing',
          'Real exposure',
          'Concentration risk',
          'Smart beta',
          'Net performance',
          'Fund selection checklist',
        ],
      },
      {
        title: 'Analysing Real Estate',
        coreQuestion: 'How can one judge a real estate investment without self-deception?',
        lessons: [
          'Price per square metre',
          'Gross, net, and net-net yield',
          'Rental vacancy',
          'Charges and works',
          'Taxation',
          'Leverage',
          'Real estate cash flow',
          'Capitalization rate',
          'SCPI: yield and risks',
          'Listed real estate',
          'Downside scenarios',
          'Decision: buy, rent, or wait',
        ],
      },
      {
        title: 'Analysing Alternative Assets and Crypto',
        coreQuestion: 'How can one approach speculative assets without being pulled in?',
        lessons: [
          'Gold and commodities',
          'Private equity accessible to individuals',
          'Structured products',
          'Crypto-assets',
          'Stablecoins',
          'Staking and lending',
          'NFTs and digital assets',
          'Liquidity and difficult valuation',
          'Counterparty risk',
          'Regulatory risk',
          'Frauds and red flags',
          'Limit alternative exposure',
        ],
      },
    ],
  },
  {
    code: 'G',
    name: 'Wealth Optimisation',
    emoji: '💎',
    objective:
      'Transform an isolated investment strategy into a coherent wealth architecture integrating taxation, wrappers, real estate, retirement, transmission, family protection, and life objectives.',
    modules: [
      {
        title: 'Wealth Objectives and Personal Balance Sheet',
        coreQuestion: 'How can one build a strategy adapted to real life?',
        lessons: [
          'Wealth balance sheet',
          'Short-, medium-, and long-term objectives',
          'Time horizon',
          'Savings capacity',
          'Risk capacity',
          'Liquidity needs',
          'Real estate project',
          'Retirement',
          'Protection of loved ones',
          'Financial independence',
          'Prioritization of objectives',
          'Personal wealth plan',
        ],
      },
      {
        title: 'Tax Wrappers and Order of Investment',
        coreQuestion: 'Where should one invest before choosing what to buy?',
        lessons: [
          'PEA',
          'CTO',
          'Life insurance',
          'PER',
          'Regulated savings accounts',
          'Term deposit',
          'Taxation of dividends',
          'Taxation of capital gains',
          'Taxation of bonds',
          'Taxation of ETFs',
          'Real estate taxation',
          'Optimal order of use of tax wrappers',
        ],
      },
      {
        title: 'Wealth Real Estate and Taxation',
        coreQuestion: 'How can real estate be integrated without unbalancing the entire wealth structure?',
        lessons: [
          'Primary residence',
          'Rental investment',
          'LMNP',
          'SCI',
          'SCPI',
          'Mortgage credit',
          'Borrower insurance',
          'Property income taxation',
          'Real estate leverage',
          'Concentration risk',
          'Arbitrating between real estate and financial markets',
          'Long-term real estate strategy',
        ],
      },
      {
        title: 'Retirement, FIRE, and Financial Independence',
        coreQuestion: 'How can capital be transformed into future freedom?',
        lessons: [
          'Savings rate',
          'Target capital',
          'The 4% rule and its limits',
          'Passive income',
          'PER and retirement',
          'Life insurance and annuity',
          'Sequence of returns',
          'Inflation during retirement',
          'Health protection and dependency',
          'Realistic FIRE vs. fantasy',
          'Transition plan',
          'Personal retirement table',
        ],
      },
      {
        title: 'Transmission, Protection, and Wealth Organization',
        coreQuestion: 'How can what has been built be protected?',
        lessons: [
          'Death insurance',
          'Personal protection insurance',
          'Matrimonial regime',
          'Donation',
          'Inheritance',
          'Beneficiary clause',
          'Protection of the spouse',
          'Protection of children',
          'Legal diversification',
          'Essential documents',
          'Family dialogue about money',
          'Annual wealth maintenance plan',
        ],
      },
    ],
  },
  {
    code: 'H',
    name: 'Advanced Finance for Demanding Individuals',
    emoji: '⚙️',
    objective:
      'Give an advanced individual the conceptual tools of modern finance without turning them into an institutional investor: understand derivatives, factors, volatility, extreme risk, and professional techniques useful for robust personal management.',
    modules: [
      {
        title: 'Derivatives: Protection Tools or Weapons of Destruction?',
        coreQuestion: 'Why can derivatives protect or ruin?',
        lessons: [
          'Forwards, futures, options, and swaps',
          'Economic usefulness of derivatives',
          'Leverage',
          'Index futures',
          'Call and put options',
          'Payoff and simple diagrams',
          'Hedging vs. speculation',
          'Counterparty risk',
          'Margin and margin calls',
          'Structured products',
          'When to avoid derivatives',
          'Prudence rules for individuals',
        ],
      },
      {
        title: 'Options and Volatility',
        coreQuestion: 'Why does the price of an option depend on more than market direction?',
        lessons: [
          'Intrinsic value and time value',
          'Implied volatility',
          'Black-Scholes: intuition',
          'Delta',
          'Gamma',
          'Theta',
          'Vega',
          'Simple strategies: protective put, covered call',
          'Risk of sold options',
          'Volatility skew and smile',
          'Options during crises',
          'Checklist before any option trade',
        ],
      },
      {
        title: 'Factor Investing and Smart Beta',
        coreQuestion: 'Why do some market premia appear to persist?',
        lessons: [
          'Market beta',
          'Value factor',
          'Size factor',
          'Momentum factor',
          'Quality factor',
          'Low volatility factor',
          'Fama-French',
          'Smart beta ETFs',
          'Factor crowding',
          'Factor cycles',
          'Factor diversification',
          'Use factors without over-optimizing',
        ],
      },
      {
        title: 'Quantitative Finance Useful to Individuals',
        coreQuestion: 'Which quantitative tools are really worth understanding?',
        lessons: [
          'Arithmetic return vs. geometric return',
          'Annualized volatility',
          'Sharpe ratio',
          'Sortino ratio',
          'Beta',
          'Tracking error',
          'Maximum drawdown',
          'Backtest and data biases',
          'Over-optimization',
          'GARCH: intuition of variable volatility',
          'Copulas: intuition of dependence',
          'Build an advanced risk table',
        ],
      },
      {
        title: 'Extreme Risk and Robust Portfolio',
        coreQuestion: 'How can one think about rare events that destroy fragile plans?',
        lessons: [
          'Fat tails',
          'Mandelbrot and non-Gaussian markets',
          'Taleb and antifragility',
          'Extreme value theory',
          'Correlations that rise during crises',
          'Historical stress test',
          'Hypothetical stress test',
          'Liquidity during crises',
          'Model risk',
          'Operational risk',
          'Extreme survival plan',
          'Transform a fragile portfolio into a robust portfolio',
        ],
      },
    ],
  },
];

// ─── Premium references (syllabus appendix) ───────────────────────────────

export const SYLLABUS_REFERENCES: string[] = [
  'Benjamin Graham - The Intelligent Investor',
  'John C. Bogle - The Little Book of Common Sense Investing',
  'Burton Malkiel - A Random Walk Down Wall Street',
  'Morgan Housel - The Psychology of Money',
  'Daniel Kahneman - Thinking, Fast and Slow',
  'Nassim Nicholas Taleb - Antifragile',
  'Howard Marks - The Most Important Thing',
  'Ray Dalio - Principles for Dealing with the Changing World Order',
  'Bodie, Kane and Marcus - Investments',
  'Aswath Damodaran - Investment Valuation',
  'Fama and French - Factor Investing Research Papers',
  'Markowitz - Portfolio Selection',
  'Black and Scholes - The Pricing of Options and Corporate Liabilities',
  'BIS - Financial Stability Reports',
  'AMF France - Educational Guides for Investors',
  'JP Morgan - Guide to the Markets',
  'AQR - Research Papers',
];

// ─── Derived helpers ───────────────────────────────────────────────────────

export const domainId = (code: string) => `dom-${code.toLowerCase()}`;
export const moduleId = (code: string, mIndex: number) => `${code.toLowerCase()}-m${mIndex + 1}`;
export const lessonId = (code: string, mIndex: number, lIndex: number) =>
  `${code.toLowerCase()}-m${mIndex + 1}-l${lIndex + 1}`;

export const SYLLABUS_TOTALS = {
  domains: SYLLABUS.length,
  modules: SYLLABUS.reduce((n, d) => n + d.modules.length, 0),
  lessons: SYLLABUS.reduce((n, d) => n + d.modules.reduce((m, mod) => m + mod.lessons.length, 0), 0),
};
